kind: Secret
apiVersion: v1
metadata:
  name: mattermost.env
  namespace: default
type: Opaque
data:
  # see http://kubernetes.io/docs/user-guide/secrets/#creating-a-secret-using-kubectl-create-secret
  # for creating secrets manually
    # db
  db-host: ZGI=
    # 5432
  db-port: NTQzMg==
    # mmuser
  mm-username: bW11c2Vy
    # mmuser_password
  mm-password: bW11c2VyX3Bhc3N3b3Jk
    # mattermost
  mm-dbname: bWF0dGVybW9zdA==
